export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY" ;
export const CREATE_CATEGORY = "CREATE_CATEGORY" ;
export const GET_ONE_CATEGORY = "GET_ONE_CATEGORY" ;


export const CREATE_SUB_CATEGORY = "CREATE_SUB_CATEGORY" ;
export const GET_SPECIFIED_SUB_CATEGORY = "GET_SPECIFIED_SUB_CATEGORY" ;

export const GET_ALL_BRAND = "GET_ALL_BRAND" ;
export const CREATE_BRAND = "CREATE_BRAND" ;
export const GET_ONE_BRAND = "GET_ONE_BRAND" ;


export const CREATE_PRODUCT = "CREATE_PRODUCT" ;
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT" ;
export const GET_ONE_PRODUCT = "GET_ONE_PRODUCT" ;
export const GET_PRODUCT_LIKE = "GET_PRODUCT_LIKE" ;
export const DELETE_PRODUCT = "DELETE_PRODUCT" ;
export const UPDATE_PRODUCT = "UPDATE_PRODUCT" ;



export const CREATE_NEW_USER = "CREATE_NEW_USER" ;
export const LOGIN_USER = "LOGIN_USER" ;
export const FORGET_PASSWORD = "FORGET_PASSWORD" ;



export const CREATE_REVIEW = "CREATE_REVIEW" ;
export const ALL_REVIEW_PRODUCT = "ALL_REVIEW_PRODUCT" ;
export const DELETE_REVIEW_PRODUCT = "DELETE_REVIEW_PRODUCT" ;
export const UPDATE_REVIEW_PRODUCT = "UPDATE_REVIEW_PRODUCT" ;



export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST" ;
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST" ;
export const USER_All_WISHLIST = "USER_All_WISHLIST" ;


export const GET_ERROR = "GET_ERROR"